# Generated by Django 5.2 on 2025-04-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256, verbose_name='پرسش')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'پرسش',
                'verbose_name_plural': 'پرسش و پاسخ',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('location', models.URLField(max_length=1024, verbose_name='لینک گوگل مپ')),
                ('phone', models.CharField(max_length=16, verbose_name='شماره')),
                ('phone_office', models.CharField(max_length=16, verbose_name='شماره دفتر')),
                ('instagram', models.CharField(max_length=48, verbose_name='اینستاگرام')),
                ('whatsapp', models.URLField(max_length=256, verbose_name='لینک واتس آپ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'راه ارتباطی',
                'verbose_name_plural': 'راه ارتباطی',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48, verbose_name='نام')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='عکس')),
                ('job', models.CharField(max_length=48, verbose_name='سمت')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره')),
                ('content', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('whatsapp', models.URLField(blank=True, max_length=256, null=True, verbose_name='لینک واتس آپ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'پرسنل',
                'verbose_name_plural': 'پرسنل',
            },
        ),
        migrations.CreateModel(
            name='FirstContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='نام سایت')),
                ('description', models.TextField(verbose_name='توضیحات اولیه')),
                ('photo', models.ImageField(upload_to='logo/', verbose_name='لوگو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نام و لوگو',
                'verbose_name_plural': 'نام و لوگو',
            },
        ),
        migrations.CreateModel(
            name='MainDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='نام سایت')),
                ('content', models.TextField(verbose_name='توضیحات تکمیلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'خدمات ما',
                'verbose_name_plural': 'خدمات ما',
            },
        ),
    ]
