# Generated by Django 5.2 on 2025-04-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48, verbose_name='نام')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='عکس')),
                ('job', models.CharField(max_length=48, verbose_name='سمت')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره')),
                ('content', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('whatsapp', models.URLField(blank=True, max_length=256, null=True, verbose_name='لینک واتس آپ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'پرسنل',
                'verbose_name_plural': 'پرسنل',
            },
        ),
    ]
