# Generated by Django 5.2 on 2025-04-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0002_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maindescription',
            name='description',
        ),
    ]
