# Generated by Django 5.2 on 2025-04-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان مقاله')),
                ('title_2', models.CharField(max_length=300, unique=True, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=400, verbose_name='عنوان url')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='images/articles', verbose_name='تصویر مقاله')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اخرین آپدیت')),
                ('is_active', models.BooleanField(default=False, verbose_name='نمایش در صفحه اول')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان مقاله')),
                ('content', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/articles', verbose_name='تصویر مقاله')),
            ],
            options={
                'verbose_name': 'توضیحات مقاله',
                'verbose_name_plural': 'توضیحات مقالات',
            },
        ),
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'محصول پیشنهادی',
                'ordering': ('primary', '-rank'),
            },
        ),
    ]
