# Generated by Django 5.2 on 2025-04-18 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='articledetail',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_detail_set', to='Blog.article', verbose_name='مقاله'),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='primary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_recommendation', to='Blog.article'),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='recommended_products',
            field=models.ManyToManyField(blank=True, through='Blog.ProductRecommendation', to='Blog.article'),
        ),
        migrations.AlterUniqueTogether(
            name='productrecommendation',
            unique_together={('primary', 'recommendation')},
        ),
    ]
