# Generated by Django 5.2 on 2025-04-20 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان بنر')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/articles', verbose_name='تصویر بنر')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_link_set', to='Blog.article', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'لینک مقاله',
                'verbose_name_plural': 'لینک مقالات',
            },
        ),
    ]
