# Generated by Django 5.2 on 2025-04-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='recommended_products',
            field=models.ManyToManyField(blank=True, null=True, through='Blog.ProductRecommendation', to='Blog.article'),
        ),
    ]
