# Generated by Django 5.2 on 2025-04-17 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_article_recommended_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='recommended_products',
            field=models.ManyToManyField(blank=True, through='Blog.ProductRecommendation', to='Blog.article'),
        ),
        migrations.AlterField(
            model_name='productrecommendation',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.article'),
        ),
    ]
