# Generated by Django 5.2 on 2025-04-10 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='عنوان دسته بندی')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='عکس دسته بندی')),
                ('url_title', models.CharField(max_length=200, unique=True, verbose_name='عنوان انگلیسی در url')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, editable=False, verbose_name='عنوان در url')),
                ('create_date', models.DateTimeField(null=True, verbose_name='تاریخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.article', verbose_name='مقاله های مرتبط')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.category', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'دسته بندی محصولات',
                'verbose_name_plural': 'دسته بندی های محصولات',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='AnswerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256, verbose_name='پرسش')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_detail', to='Product.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'پرسش',
                'verbose_name_plural': 'پرسش و پاسخ',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Desciption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='عنوان محصول')),
                ('content', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_detail', to='Product.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'توضیحات محصولات',
                'verbose_name_plural': 'توضیحات محصولات',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='عنوان محصول')),
                ('content', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('photo', models.ImageField(upload_to='products/', verbose_name='عکس محصول')),
                ('is_first', models.BooleanField(default=False, verbose_name='نمایش در صفحه اول')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_detail', to='Product.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصولات',
                'verbose_name_plural': 'محصولات',
                'ordering': ('id',),
            },
        ),
    ]
