# Generated by Django 5.2 on 2025-04-12 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desciption',
            options={'ordering': ('id',), 'verbose_name': 'توضیحات دسته بندی', 'verbose_name_plural': 'توضیحات دسته بندی'},
        ),
        migrations.AlterField(
            model_name='category',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.article', verbose_name='مقاله های مرتبط'),
        ),
    ]
