# Generated by Django 5.2 on 2025-04-13 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_desciption_options_alter_category_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentcategory', to='Product.category', verbose_name='دسته بندی والد'),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(default=1, upload_to='category/', verbose_name='عکس دسته بندی'),
            preserve_default=False,
        ),
    ]
