# Generated by Django 5.2 on 2025-04-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_initial'),
        ('Product', '0003_alter_category_parent_alter_category_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='blog',
        ),
        migrations.AddField(
            model_name='category',
            name='blog',
            field=models.ManyToManyField(blank=True, null=True, to='Blog.article', verbose_name='مقاله های مرتبط'),
        ),
    ]
