# Generated by Django 5.2 on 2025-04-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_initial'),
        ('Product', '0004_remove_category_blog_category_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='blog',
            field=models.ManyToManyField(to='Blog.article', verbose_name='مقاله های مرتبط'),
        ),
    ]
