# Generated by Django 5.2 on 2025-04-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_initial'),
        ('Product', '0006_alter_category_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='blog',
            field=models.ManyToManyField(blank=True, related_name='blags_detail', to='Blog.article', verbose_name='مقاله های مرتبط'),
        ),
    ]
